### PR TITLE
Add CSHTML support, and a minor bug fix.

### PR DESCRIPTION
**Pull request by ApacheTech**
This adds support for Razor Pages, and MVC Views.

Plus, a minor bug fix; the wrong method was being removed as a listener, when build processor is disposed.

### CODE REVIEW

**Comment by theron-wang** [comment]
Thanks for pointing out the bug!

As for the Razor Pages and MVC Views support, I could not find a `cshtml` content type from `IContentTypeRegistryService .ContentTypes`. I tested it on my end, and it appears that the `razor` content type still works for cshtml files.

Nonetheless, thank you for your contribution and bug fix!

**Comment by theron-wang** [comment]
Just a note that I will be closing this PR but I will commit the bug fix.

**Comment by ApacheTech** [comment]
Ahh, fair enough. I thought that was looking at file extensions. In my project, it works with `.css`, and `.html` pages. I get the intellisense coming through ok. But not with `.cshtml` or `.razor`. Be it Razor Pages, or Razor Views.

**Comment by ApacheTech** [comment]
A snippet of code would just be:

Solution Exporer -> Right-Click -> Add Item -> NewFile.cshtml OR NewFile.razor

And then just add...

```
<p class=""></p>
```

However, if you create `NewFile.html`, and do the same, you get the intellisense working fine.

With all CSS files, it works ok; `.css`, `.scss`, `.less`, `.sss`, the intellisense works fine, with just this:

```
* {
    @apply 
}
```

**Pull request closed without merging**
